# Generated by Django 5.1.1 on 2024-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
