# Generated by Django 5.1.1 on 2024-10-12 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_timerecord_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.tasks'),
        ),
    ]
